apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-media-server-pv
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/config"