apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-pvc
  namespace: media-server
spec:
  storageClassName: ""
  volumeName: config-media-server-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi