apiVersion: v1
kind: PersistentVolume
metadata:
  name: external-drive1-media-server-pv
spec:
  storageClassName: ""
  capacity:
    storage: 930Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: NFS_IP
    path: "/volumeUSB1/usbshare"
    readOnly: false