apiVersion: v1
kind: PersistentVolume
metadata:
  name: render-device-pv
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /dev/dri/renderD128
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: card-device-pv
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /dev/dri/card0