{{- if .Values.serverr.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "media-server.serviceAccountName" . }}
  labels:
    {{- include "media-server.labels" . | nindent 4 }}
  {{- with .Values.serverr.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
