{{- if .Values.sonarr.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sonarr.serviceAccountName" . }}
  labels:
    {{- include "sonarr.labels" . | nindent 4 }}
  {{- with .Values.sonarr.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
