{{- if .Values.radarr.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.radarr.name }}
  labels:
    {{- include "media-server-stack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.radarr.service.type }}
  ports:
    - port: {{ .Values.radarr.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.radarr.name }}
{{- end }}
