{{- if .Values.radarr.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "radarr.serviceAccountName" . }}
  labels:
    {{- include "radarr.labels" . | nindent 4 }}
  {{- with .Values.radarr.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
