{{- if .Values.jackett.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jackett.serviceAccountName" . }}
  labels:
    {{- include "jackett.labels" . | nindent 4 }}
  {{- with .Values.jackett.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
